version: '3.7'

services:
  midjourney-redis:
    image: redis:alpine
    container_name: midjourney-redis
    hostname: midjourney-redis
    ports:
      - '6379:6379'
    expose:
      - '6379'
    networks:
      - default
  midjourney-proxy:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./myconfig:/home/spring/config
      - ./logs:/home/spring/logs
    ports:
      - 8080:8080
      - 9876:9876
    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=85 -Djava.awt.headless=true -XX:+HeapDumpOnOutOfMemoryError -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -Xlog:gc:file=/home/spring/logs/gc.log -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9876 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dlogging.file.path=/home/spring/logs -Dserver.port=8080 -Duser.timezone=Asia/Shanghai
    networks:
      - default